Repository part4-6team/Coworkers, pull requests merged in 2024-11, with the labels that each got.

#85 ZERO-134 : 팀페이지 drag and drop
  src/api/tasks/taskListAPI.ts
  src/components/@shared/LoadingSpinner.tsx
  src/components/team/taskList/DeleteTaskListModal.tsx
  src/components/team/taskList/EditTaskListModal.tsx
  src/components/team/taskList/TaskBar.tsx
  src/components/team/taskList/TaskList.tsx
  src/hooks/useDragAndDrop.ts
  src/hooks/useTaskLiskModals.ts
Labels: Feat

#86 ZERO-71: 할 일 완료 및 완료 취소 버튼 & 체크박스 기능
  src/components/article/NewArticleImage.tsx
  src/components/tasks/CheckBox.tsx
  src/components/tasks/TaskCard.tsx
  src/components/tasks/TaskSideBar.tsx
  src/stores/taskListStore.ts
  src/types/tasks/taskDto.ts
Labels: Feat

#89 ZERO-149: 유저 기능 관련 페이지 개선
  src/components/@shared/NavBar.tsx
  src/components/@shared/NavBar_Team.tsx
  src/hooks/mysetting/useUserData.ts
  src/pages/oauth/google.tsx
  src/pages/oauth/kakao.tsx
  src/pages/signin/index.tsx
  src/pages/signup/index.tsx
  src/stores/useUserStore.ts
Labels: Feat, Refactor

#87 ZERO-147 : 게시글 수정/삭제 기능
  src/api/article/CommentCardAPI.tsx
  src/api/mysetting/inputAPI.ts
  src/components/article/ArticleCard.tsx
  src/components/article/ArticleCardDeletModal.tsx
  src/components/article/BestCard.tsx
  src/components/article/CommentDeletModal.tsx
  src/components/article/CommentForm.tsx
  src/components/article/CommentList.tsx
  src/components/article/DetailCard.tsx
  src/components/article/Heart.tsx
  src/components/article/NewArticleImage.tsx
  src/components/article/NoAccessModal.tsx
  src/components/myhistory/MyTask.tsx
  src/components/mysetting/RemoveAccount.tsx
  src/components/mysetting/inputTask.tsx
  src/hooks/article/useCommentAdd.tsx
  src/hooks/article/useCommentDelete.tsx
  src/hooks/article/useCommentEdit.tsx
  src/hooks/mysetting/useNicknameChange.ts
  src/pages/article/edit/[articleId].tsx
  src/types/mysetting/settingData.ts
Labels: Feat, Fix

#88 ZERO-150: 리스트페이지 1차 디버깅
  package-lock.json
  package.json
  src/components/@shared/SideBar.tsx
  src/components/tasks/AddTaskForm.tsx
  src/components/tasks/Calender.tsx
  src/components/tasks/Layout/TaskList.tsx
  src/components/tasks/UI/AddTaskListModal.tsx
  src/contexts/DateContext.tsx
  src/styles/calendar.module.css
Labels: Fix

#94 ZERO-154: 유저 기능 1차 QA
  src/components/auth/SignInForm.tsx
  src/components/auth/SignUpForm.tsx
  src/pages/_app.tsx
Labels: Feat, Refactor

#93 ZERO-155 : 계정설정페이지 1차 QA 피드백 반영
  package-lock.json
  package.json
  src/components/mysetting/PasswordInput.tsx
  src/components/mysetting/RemoveAccount.tsx
  src/components/mysetting/ShareModal.tsx
  src/components/mysetting/inputTask.tsx
Labels: Fix

#92 ZERO-153 : 팀페이지 1차 디버깅
  public/images/user_not_found.png
  src/components/@shared/Dropdown.tsx
  src/components/@shared/NavBar_Team.tsx
  src/components/@shared/UserNotFound.tsx
  src/components/team/banner/DeleteTeamModal.tsx
  src/components/team/banner/EditTeamModal.tsx
  src/components/team/member/ExileDropdown.tsx
  src/components/team/member/GetUserDetailModal.tsx
  src/components/team/taskList/TaskBar.tsx
  src/components/team/taskList/TaskList.tsx
  src/pages/[teamid]/index.tsx
  src/pages/myteam/index.tsx
  src/styles/scroll.module.css
Labels: Feat, Fix

#90 ZERO-147 : 네브바 버그 수정
  src/components/@shared/NavBar.tsx
  src/components/@shared/NavBar_Team.tsx
  src/hooks/mysetting/useUserData.ts
Labels: Fix

#91 ZERO-152 : 공통 - 모달 스크롤
  src/components/@shared/Modal.tsx
  src/components/team/taskList/TaskList.tsx
  src/styles/globals.css
Labels: Fix

#95 ZERO-125 : 네브바 로고 중복 버그 수정
  src/components/@shared/NavBar.tsx
Labels: Fix

#97 ZERO-157 : 마이히스토리 페이지 랜더링 오류 수정
  src/components/myhistory/MyTask.tsx
Labels: Fix

#96 ZERO-155 : 닉네임 변경 글자 제한
  src/components/mysetting/inputTask.tsx
Labels: Fix

#98 ZERO-158 : 게시판 페이지 QA1차 디버깅
  next.config.mjs
  src/components/article/ArrayDropdown.tsx
  src/components/article/ArticleCard.tsx
  src/components/article/BestCard.tsx
  src/components/article/CommentList.tsx
  src/components/article/DetailCard.tsx
  src/components/article/NewArticleImage.tsx
  src/pages/article/edit/[articleId].tsx
  src/pages/article/index.tsx
  src/pages/article/newarticle.tsx
Labels: Fix

#101 ZERO-156 : 메타태그, 파비콘, 폰트
  public/favicon.png
  public/fonts/PretendardVariable.woff
  src/components/team/taskList/TaskList.tsx
  src/pages/_app.tsx
  src/styles/globals.css
  src/styles/scroll.module.css
Labels: Fix, Chore, Rename

#100 ZERO-161: 할 일 목록 페이지네이션 추가
  public/icons/plus_green.svg
  src/components/@shared/Input.tsx
  src/components/@shared/SideBar.tsx
  src/components/home/Content.tsx
  src/components/tasks/AddTaskForm.tsx
  src/components/tasks/Layout/TaskDate.tsx
  src/components/tasks/Layout/TaskList.tsx
  src/components/tasks/TaskCard.tsx
  src/components/tasks/TaskComments.tsx
  src/components/tasks/TaskDetails.tsx
  src/components/tasks/UI/AddTaskListButton.tsx
  src/components/tasks/UI/Calender.tsx
  src/components/tasks/UI/CheckBox.tsx
  src/components/tasks/UI/DatePagination.tsx
  src/components/tasks/UI/ListPagination.tsx
  src/components/tasks/UI/WeeklySelector.tsx
  src/components/tasks/UI/button/AddTaskButton.tsx
  src/components/tasks/UI/button/AddTaskListButton.tsx
  src/components/tasks/UI/button/CalenderButton.tsx
  src/components/tasks/UI/input/DescriptionTextArea.tsx
  src/components/tasks/UI/input/NameInput.tsx
  src/components/tasks/UI/modal/AddTaskListModal.tsx
  src/components/tasks/UI/modal/AddTaskModal.tsx
  src/components/tasks/UI/modal/DeleteTaskModal.tsx
  src/components/tasks/UI/modal/EditTaskModal.tsx
  src/constants/iconPaths.ts
  src/pages/[teamid]/tasks.tsx
  src/stores/taskListStore.ts
  src/styles/scroll.module.css
  src/types/tasks/commentDto.ts
  src/utils/getResponsiveValue.ts
  src/utils/getSortedDate.ts
Labels: Feat

#102 ZERO-158 : 좋아요 기능 로직 수정
  src/components/article/ArticleCard.tsx
  src/components/article/BestCard.tsx
  src/components/article/CommentList.tsx
  src/components/article/DetailCard.tsx
  src/components/article/Heart.tsx
Labels: Fix

#103 ZERO-161: 리스트 페이지 로딩 스피너 적용 & 업데이트 관련 버그 수정
  src/components/tasks/TaskDate.tsx
  src/components/tasks/TaskList.tsx
  src/pages/[teamid]/tasks.tsx
Labels: Feat, Fix

#107 Design change
  public/icons/alert.svg
  public/icons/arrow_down.svg
  public/icons/arrow_left.svg
  public/icons/arrow_right.svg
  public/icons/ic_medal.svg
  public/icons/landing_check.svg
  public/icons/landing_email.svg
  public/icons/landing_folder.svg
  public/icons/plus_green.svg
  public/icons/progress_done.svg
  public/images/donut_logo.png
  public/images/donut_logo2.png
  public/images/donut_logo3.png
  src/components/@shared/Button.tsx
  src/components/@shared/Input.tsx
  src/components/@shared/NavBar.tsx
  src/components/@shared/NavBar_Team.tsx
  src/components/@shared/NetworkError.tsx
  src/components/@shared/SideBar.tsx
  src/components/home/Banner.tsx
  src/components/team/Report.tsx
  src/components/team/taskList/TaskBar.tsx
  src/styles/calendar.module.css
  src/styles/globals.css
  src/styles/scroll.module.css
  tailwind.config.ts
Labels: Design

#105 ZERO-163: 404 페이지
  next.config.mjs
  src/components/@shared/NavBar.tsx
  src/components/@shared/UserNotFound.tsx
  src/pages/404.tsx
Labels: Fix, Design

#106 ZERO-125 : 네브바 버그 수정
  src/components/@shared/NavBar.tsx
  src/components/article/ArticleCard.tsx
Labels: Fix

#109 ZERO-166 : 테마색상 변경 및 TaskBar 로직 일부 변경
  public/icons/checkbox_active.svg
  public/icons/enter_active.svg
  public/icons/progress_done.svg
  public/images/graph_done.png
  src/components/@shared/NavBar_Team.tsx
  src/components/team/Report.tsx
  src/components/team/banner/TeamBanner.tsx
  src/components/team/myteam/TeamBox.tsx
  src/components/team/taskList/TaskBar.tsx
  src/components/team/taskList/tagColors.ts
Labels: Feat, Chore, Design

#108 ZERO-168 : 게시판페이지 애니메이션 추가
  package-lock.json
  package.json
  public/icons/articleLoadingSpinner.svg
  src/components/article/ArticleCard.tsx
  src/components/article/BestCard.tsx
  src/components/article/Heart.tsx
Labels: Chore, Design

#110 ZERO-170 : 자잘한 버그 수정
  public/favicon.png
  public/images/thumbnail.png
  src/components/@shared/Button.tsx
  src/components/@shared/Input.tsx
  src/components/@shared/NavBar_Team.tsx
  src/components/@shared/createTeamOption.tsx
  src/components/team/MoreIcon.tsx
  src/components/team/taskList/TaskList.tsx
  src/pages/_app.tsx
Labels: Fix

#112 ZERO-172: 회원가입 시 랜덤 도넛 프로필 지정(추가 기능) 및 디자인 수정
  public/images/angry_choco.png
  public/images/boss.png
  public/images/choco.png
  public/images/choco_ring.png
  public/images/cute_strawberry.png
  public/images/egg.png
  public/images/glazed.png
  public/images/happy_soda.png
  public/images/lemon.png
  public/images/pistachio.png
  public/images/smile_lemon.png
  public/images/soda.png
  public/images/strawberry.png
  public/images/strawberry2.png
  src/api/auth/imageAPI.ts
  src/components/@shared/UserNotFound.tsx
  src/components/auth/SignUpForm.tsx
  src/components/mysetting/PasswordChange.tsx
  src/utils/getRandomDonut.ts
Labels: Feat, Design

#113 ZERO-171 : 버그 수정 및 프로필 기본 이미지 적용
  src/components/@shared/NavBar_Team.tsx
  src/components/@shared/createTeamOption.tsx
  src/components/article/ArticleCard.tsx
  src/components/article/NewArticleImage.tsx
  src/components/mysetting/inputTask.tsx
  src/hooks/mysetting/useProfileChange.ts
  src/pages/mysetting/index.tsx
  src/types/mysetting/settingData.ts
Labels: Feat, Fix

#114 ZERO-100: 리스트 페이지 & 공통 모달 애니메이션
  src/components/@shared/DonutLoadingSpinner.tsx
  src/components/@shared/Modal.tsx
  src/components/@shared/animation/CardMotion.tsx
  src/components/@shared/animation/ClickMotion.tsx
  src/components/@shared/animation/FadeInMotion.tsx
  src/components/@shared/animation/IconSparkleMotion.tsx
  src/components/@shared/animation/SlideDownMotion.tsx
  src/components/@shared/animation/SlideInMotion.tsx
  src/components/@shared/animation/SlideItemsMotion.tsx
  src/components/@shared/animation/TextButtonMotion.tsx
  src/components/home/Banner.tsx
  src/components/home/Content.tsx
  src/components/home/Footer.tsx
  src/components/tasks/AddTaskForm.tsx
  src/components/tasks/TaskCard.tsx
  src/components/tasks/TaskComments.tsx
  src/components/tasks/TaskDate.tsx
  src/components/tasks/TaskDetails.tsx
  src/components/tasks/TaskList.tsx
  src/components/tasks/UI/Calender.tsx
  src/components/tasks/UI/CheckBox.tsx
  src/components/tasks/UI/DatePagination.tsx
  src/components/tasks/UI/ListPagination.tsx
  src/components/tasks/UI/button/AddTaskButton.tsx
  src/components/tasks/UI/button/AddTaskListButton.tsx
  src/components/tasks/UI/button/CalenderButton.tsx
  src/constants/iconPaths.ts
  src/hooks/usePagnation.tsx
  src/pages/[teamid]/tasks.tsx
  src/styles/carAnimation.module.css
Labels: Design

#116 ZERO-173 : 랜딩페이지 애니메이션
  package-lock.json
  package.json
  public/images/landing_background.png
  public/images/landing_banner_logo.png
  public/images/landing_bottom_1.png
  public/images/landing_bottom_2.png
  public/images/landing_donut_1.png
  public/images/landing_donut_2.png
  public/images/landing_donut_3.png
  public/images/landing_footer.png
  public/images/landing_footer_mb.png
  public/images/landing_ment.png
  public/images/landing_mid_1.png
  public/images/landing_mid_2.png
  public/images/landing_top_1.png
  public/images/landing_top_2.png
  public/images/landing_top_box_pc.png
  public/images/landing_train.png
  src/components/home/Banner.tsx
  src/components/home/Content.tsx
  src/components/home/Footer.tsx
  src/constants/imagePaths.ts
Labels: Design

#115 ZERO-171 : 계정설정 페이지 토스트 적용
  public/icons/erroricon.svg
  public/icons/successicon.svg
  src/components/article/Snackbar.tsx
  src/components/mysetting/inputTask.tsx
Labels: Feat

#118 ZERO-174 : 할일 완료 그래프 추가(잔디)
  src/components/myhistory/Contributions.tsx
  src/pages/myhistory/[id].tsx
Labels: Feat

#121 ZERO-176: css 파일 경로 에러 수정
  src/components/@shared/animation/IconSparkleMotion.tsx
  src/components/home/Content.tsx
  src/styles/sparkle.module.css
Labels: Fix

#124 CI/CD develop 브랜치 배포 자동화 GitHub Action
  .github/workflows/deploy-develop.yml
  .github/workflows/deploy.yml
Labels: Feat

#122 ZERO-174 : 잔디 가로로 수정
  package-lock.json
  package.json
  src/components/myhistory/Contributions.tsx
  src/pages/myhistory/[id].tsx
  src/styles/scroll.module.css
Labels: Chore, Design

#126 ZERO-125 : 네브바 프로필 이미지 추가
  src/components/@shared/NavBar.tsx
  src/components/article/BestCard.tsx
  src/components/article/Snackbar.tsx
  src/components/myhistory/mockdata.ts
  src/components/mysetting/inputTask.tsx
  src/components/mysetting/usermockdata.ts
  src/hooks/article/useArticleDelet.tsx
  src/hooks/article/useCommentAdd.tsx
  src/hooks/article/useCommentDelete.tsx
  src/hooks/article/useCommentEdit.tsx
  src/hooks/article/useEditArticle.tsx
  src/hooks/article/useNewArticle.tsx
  src/hooks/mysetting/useImageURL.ts
  src/hooks/mysetting/useNicknameChange.ts
  src/hooks/mysetting/usePasswordChange.ts
  src/hooks/mysetting/usePasswordCheck.ts
  src/hooks/mysetting/useProfileChange.ts
  src/hooks/mysetting/useUserDelete.ts
Labels: Feat, Fix, Design

#128 ZERO-177: 랜딩페이지 가로 스크롤 바 숨김 & 리스트 페이지 3차 QA
  src/components/@shared/animation/CardMotion.tsx
  src/components/tasks/TaskComments.tsx
  src/pages/index.tsx
Labels: Fix, Design

#127 ZERO-178 : 팀페이지 3차 디버깅
  public/icons/failIcon.svg
  public/icons/question.svg
  public/images/participate.png
  public/images/team_none_tb.png
  src/components/@shared/Dropdown.tsx
  src/components/article/Snackbar.tsx
  src/components/mysetting/inputTask.tsx
  src/components/team/CircleGraph.tsx
  src/components/team/OptionDropdown.tsx
  src/components/team/Report.tsx
  src/components/team/banner/DeleteTeamModal.tsx
  src/components/team/member/EmailInvitationModal.tsx
  src/components/team/member/GetUserDetailModal.tsx
  src/components/team/member/HowToModal.tsx
  src/components/team/member/InvitationModal.tsx
  src/components/team/member/MemberList.tsx
  src/components/team/myteam/EmptyTeamPage.tsx
  src/components/team/taskList/TaskBar.tsx
  src/components/team/taskList/TaskList.tsx
  src/hooks/useClipBoardCopy.ts
  src/pages/myteam/index.tsx
  src/styles/progress.module.css
  src/styles/scroll.module.css
  src/utils/getModalClass.tsx
  tailwind.config.ts
Labels: Feat, Fix, Chore, Design

#129 ZERO-181 : 게시판 페이지 버그 수정 및 리팩토링
  src/components/@shared/NavBar.tsx
  src/components/@shared/NavBar_Team.tsx
  src/components/@shared/ProfileImageInput.tsx
  src/components/article/ArticleCard.tsx
  src/components/article/BestCard.tsx
  src/components/article/Skeleton.tsx/ArticleCardSkeletonCard.tsx
  src/components/article/Skeleton.tsx/ArticleSkeletonUI.tsx
  src/components/article/Skeleton.tsx/BestCardSkeletonCard.tsx
  src/components/article/Skeleton.tsx/BestSkeletonUI.tsx
  src/components/mysetting/inputTask.tsx
  src/pages/article/index.tsx
  src/styles/globals.css
Labels: Feat, Fix

#130 ZERO-180: 모바일 디자인 보완 & 애니메이션 전체 페이지 일괄 적용
  src/components/@shared/BasicDropdown.tsx
  src/components/@shared/MockUserData.ts
  src/components/@shared/NavBar.tsx
  src/components/@shared/NavBar_Team.tsx
  src/components/@shared/animation/ButtonMotion.tsx
  src/components/@shared/animation/ScrollDonutBounceMotion.tsx
  src/components/@shared/animation/SlideItemsMotion.tsx
  src/components/addteam/AddTeamForm.tsx
  src/components/addteam/ParticipateTeamForm.tsx
  src/components/article/ArrayDropdown.tsx
  src/components/article/BestCard.tsx
  src/components/article/CommentList.tsx
  src/components/article/DetailCard.tsx
  src/components/auth/SignInForm.tsx
  src/components/auth/SignUpForm.tsx
  src/components/home/Banner.tsx
  src/components/home/Content.tsx
  src/components/home/Footer.tsx
  src/components/myhistory/Contributions.tsx
  src/components/myhistory/MyTask.tsx
  src/components/mysetting/inputTask.tsx
  src/components/tasks/TaskList.tsx
  src/components/tasks/UI/ListPagination.tsx
  src/components/tasks/UI/button/AddTaskListButton.tsx
  src/components/team/Report.tsx
  src/components/team/banner/TeamBanner.tsx
  src/components/team/member/MemberBox.tsx
  src/components/team/member/MemberList.tsx
  src/components/team/myteam/TeamBox.tsx
  src/pages/[teamid]/index.tsx
  src/pages/addteam/index.tsx
  src/pages/addteam/participate.tsx
  src/pages/article/index.tsx
  src/pages/article/newarticle.tsx
  src/pages/myhistory/[id].tsx
  src/pages/mysetting/[id].tsx
  src/pages/myteam/index.tsx
Labels: Design, Refactor

#131 ZERO-185 : 팀페이지 리팩토링
  src/components/@shared/Input.tsx
  src/components/@shared/NavBar_Team.tsx
  src/components/tasks/AddTaskForm.tsx
  src/components/tasks/TaskCard.tsx
  src/components/tasks/TaskComments.tsx
  src/components/tasks/TaskDate.tsx
  src/components/tasks/TaskDetails.tsx
  src/components/tasks/TaskList.tsx
  src/components/tasks/UI/CheckBox.tsx
  src/components/tasks/UI/button/AddTaskButton.tsx
  src/components/tasks/UI/modal/AddTaskListModal.tsx
  src/components/tasks/UI/modal/DeleteRecurringModal.tsx
  src/components/tasks/UI/modal/DeleteTaskModal.tsx
  src/components/tasks/UI/modal/EditTaskModal.tsx
  src/components/team/CircleGraph.tsx
  src/components/team/banner/DeleteTeamModal.tsx
  src/components/team/banner/EditTeamModal.tsx
  src/components/team/banner/TeamBanner.tsx
  src/components/team/member/EmailInvitationModal.tsx
  src/components/team/member/ExileDropdown.tsx
  src/components/team/member/ExileUserModal.tsx
  src/components/team/member/InvitationModal.tsx
  src/components/team/member/MemberBox.tsx
  src/components/team/member/MemberList.tsx
  src/components/team/myteam/EmptyTeamPage.tsx
  src/components/team/myteam/TeamBox.tsx
  src/components/team/taskList/AddTaskListModal.tsx
  src/components/team/taskList/DeleteTaskListModal.tsx
  src/components/team/taskList/EditTaskListModal.tsx
  src/components/team/taskList/TaskBar.tsx
  src/components/team/taskList/TaskList.tsx
  src/hooks/team/useAdminCheck.ts
  src/hooks/team/useTaskListStorage.ts
  src/hooks/team/useTeamValidation.ts
  src/hooks/useDragAndDrop.ts
  src/hooks/useImageUpload.ts
  src/pages/[teamid]/index.tsx
  src/pages/[teamid]/tasks.tsx
  src/pages/myteam/index.tsx
  src/stores/useTaskListStore.ts
  src/stores/useTeamStore.ts
Labels: Feat, Fix, Rename, Refactor

#132 App 배포 전 README 작성
  README.md
Labels: Docs
