Repository part4-6team/Coworkers, pull requests merged in 2024-10, with the labels that each got.

#3 ZERO-26 : 테스트 페이지 제작
  package-lock.json
  package.json
  postcss.config.js
  src/pages/_document.tsx
  src/pages/fonts/PretendardVariable.woff
  src/pages/index.tsx
  src/pages/test/index.tsx
  src/styles/globals.css
  tailwind.config.ts
Labels: Feat, Chore

#5 ZERO-27: 공통컴포넌트 버튼 추가
  package-lock.json
  package.json
  src/pages/components/@shared/Button.tsx
  src/pages/test/index.tsx
  src/styles/globals.css
  tailwind.config.ts
Labels: Feat

#7 ZERO-28: 공통 컴포넌트 input 제작 + tailwind 오류 수정
  src/pages/components/@shared/Input.tsx
  src/pages/test/index.tsx
  src/styles/globals.css
  src/styles/scroll.module.css
  tailwind.config.ts
Labels: Feat

#9 ZERO-23: 공통 컴포넌트 Modal 제작
  package-lock.json
  src/components/@shared/Modal.tsx
  src/hooks/useModal.tsx
  src/pages/test/index.tsx
  src/utils/getModalClass.tsx
Labels: Feat

#12 ZERO-81: develop 브랜치 파일 구조 변경
  src/api/hello.ts
  src/components/@shared/Button.tsx
  src/components/@shared/Input.tsx
  src/fonts/PretendardVariable.woff
  src/pages/test/index.tsx
Labels: Rename

#10 ZERO-47 마이 히스토리 퍼블리싱
  package-lock.json
  package.json
  src/components/@shared/SideBar.tsx
  src/components/myhistory/MyTask.tsx
  src/pages/myhistory/index.tsx
Labels: Chore, Design

#11 ZERO-54: 회원가입 페이지 퍼블리싱
  src/components/@shared/SideBar.tsx
  src/components/auth/Divider.tsx
  src/components/auth/GoogleOauthButton.tsx
  src/components/auth/KaKaoOauthButton.tsx
  src/components/auth/SignUpForm.tsx
  src/pages/signup/index.tsx
  src/pages/test/index.tsx
Labels: Design

#14 ZERO-49: 로그인 페이지 퍼블리싱
  src/components/auth/SignInForm.tsx
  src/components/auth/SignUpForm.tsx
  src/pages/signin/index.tsx
Labels: Feat, Design

#15 ZERO-48 : 마이히스토리 페이지 데이터 패칭
  src/components/@shared/NavBar.tsx
  src/components/myhistory/MyTask.tsx
  src/lib/axios.tsx
  src/pages/_app.tsx
  src/pages/myhistory/index.tsx
Labels: Feat, Chore

#18 Zero 48 myhistory data fatch
  src/components/myhistory/MyTask.tsx
  src/lib/axios.tsx
Labels: Fix

#19 ZERO-29 : 사이드바 테스트페이지 추가
  src/components/@shared/SideBar.tsx
  src/pages/test/sidebar/index.tsx
Labels: Feat, Design

#20 ZERO-51: 로그인 프로토타입 제작
  src/components/auth/SignInForm.tsx
  src/pages/signin/index.tsx
Labels: Feat

#23 ZERO-56: 회원가입 유효성 검사
  src/components/auth/Divider.tsx
  src/components/auth/SignUpForm.tsx
  src/pages/signup/index.tsx
Labels: Feat

#21 ZERO-25 : NavBar 드랍다운 기능 추가
  src/components/@shared/NavBar.tsx
Labels: Refactor

#22 ZERO-84: 버튼 컴포넌트 비활성화 스타일 추가
  src/components/@shared/Button.tsx
  src/pages/test/index.tsx
Labels: Feat, Design

#24 ZERO-42: 랜딩페이지 퍼블리싱
  public/icons/landing_check.svg
  public/icons/landing_email.svg
  public/icons/landing_folder.svg
  public/images/landing_invite.png
  public/images/landing_team.png
  public/images/landing_todo.png
  public/images/landing_train_mb.png
  public/images/landing_train_pc.png
  public/images/landing_train_tb.png
  src/components/@shared/Modal.tsx
  src/constants/iconPaths.ts
  src/constants/imagePaths.ts
  src/pages/index.tsx
  src/styles/globals.css
  tailwind.config.ts
Labels: Design

#26 ZERO-48 : 마이히스토리 페이지 수정
  package-lock.json
  package.json
  src/api/myhistory/taskAPI.ts
  src/components/@shared/SideBar.tsx
  src/components/myhistory/MyTask.tsx
  src/components/myhistory/mockdata.ts
  src/hooks/myhistory/useDeleteTask.ts
  src/hooks/myhistory/useTask.ts
  src/types/myhistory/TaskType.ts
Labels: Feat, Fix, Chore, Refactor

#25 ZERO-52: 로그인 유효성 검사
  src/components/auth/SignInForm.tsx
  src/components/auth/SignUpForm.tsx
Labels: Feat

#27 ZERO-43: 리스트페이지 퍼블리싱 & Dropdown 수정
  docs/pull_request_template.md
  public/icons/calendar_large.svg
  src/components/@shared/Dropdown.tsx
  src/components/tasks/TaskCard.tsx
  src/components/tasks/TaskDate.tsx
  src/components/tasks/Tasks.tsx
  src/components/tasks/UI/Calender.tsx
  src/components/tasks/UI/CheckBox.tsx
  src/components/tasks/UI/CreateTask.tsx
  src/components/tasks/UI/CreateTaskList.tsx
  src/components/tasks/UI/Pagination.tsx
  src/constants/iconPaths.ts
  src/pages/[teamid]/tasks/index.tsx
  src/pages/_app.tsx
Labels: Fix, Design

#29 ZERO-48 : 네트워크 에러처리, 사이드바 수정
  public/icons/networkErrorIcon.png
  src/components/@shared/SideBar.tsx
  src/components/myhistory/MyTask.tsx
  src/pages/test/sidebar/index.tsx
Labels: Fix, Refactor

#30 ZERO-25 : Navbar 반응형 수정
  src/components/@shared/NavBar.tsx
Labels: Refactor

#31 ZERO-85: 랜딩페이지 리팩토링
  src/components/home/Banner.tsx
  src/components/home/Content.tsx
  src/components/home/Footer.tsx
  src/hooks/useResponsiveImageDetails.tsx
  src/hooks/useViewportSize.tsx
  src/pages/index.tsx
Labels: Refactor

#33 ZERO-92 : 계정설정 페이지 모달추가, 프로필 설정 로직 추가
  src/api/mysetting/inputAPI.ts
  src/components/mysetting/PasswordChange.tsx
  src/components/mysetting/RemoveAccount.tsx
  src/components/mysetting/inputTask.tsx
  src/components/mysetting/usermockdata.ts
  src/hooks/mysetting/useUserData.ts
  src/hooks/mysetting/useUserDelete.ts
  src/pages/myhistory/[id].tsx
  src/pages/mysetting/[id].tsx
  src/types/mysetting/settingData.ts
Labels: Feat

#34 ZERO-44: 리스트페이지 mockdata 테스트 & context 추가
  package-lock.json
  src/api/tasks/taskAPI.ts
  src/api/tasks/taskListAPI.ts
  src/components/tasks/TaskCard.tsx
  src/components/tasks/TaskDate.tsx
  src/components/tasks/TaskList.tsx
  src/components/tasks/Tasks.tsx
  src/components/tasks/mockdata.ts
  src/contexts/DateContext.tsx
  src/contexts/TaskListContext.tsx
  src/pages/[teamid]/tasks/index.tsx
  src/types/tasks/TaskListDto.ts
  src/utils/getFormattedDate.tsx
Labels: Feat, Test

#35 ZERO-23: Modal 기능 추가
  src/components/@shared/Modal.tsx
Labels: Feat

#36 ZERO-68: 날짜 페이지네이션 구현 & useViewportSize 수정
  src/components/tasks/UI/Pagination.tsx
  src/hooks/useViewportSize.tsx
Labels: Feat, Fix

#37 ZERO-93: 팀페이지 모달, 드롭다운 제작
  src/components/@shared/BasicDropdown.tsx
  src/components/team/AddTaskListModal.tsx
  src/components/team/CircleGraph.tsx
  src/components/team/EditDropdown.tsx
  src/components/team/ExileDropdown.tsx
  src/components/team/GetUserDetailModal.tsx
  src/components/team/InvitationModal.tsx
  src/components/team/MemberBox.tsx
  src/components/team/MemberList.tsx
  src/components/team/TaskBar.tsx
  src/components/team/TaskList.tsx
  src/components/team/TeamBanner.tsx
Labels: Feat

#38 ZERO-98: 프로필이미지 인풋 컴포넌트 추가
  src/components/@shared/ProfileImageInput.tsx
  src/pages/test/index.tsx
Labels: Feat

#39 ZERO-92 : 계정 설정 페이지 및 모달 api 연동
  next.config.mjs
  src/api/myhistory/taskAPI.ts
  src/api/mysetting/inputAPI.ts
  src/components/@shared/NavBar.tsx
  src/components/@shared/NetworkError.tsx
  src/components/@shared/SideBar.tsx
  src/components/myhistory/MyTask.tsx
  src/components/mysetting/PasswordChange.tsx
  src/components/mysetting/PasswordErrorModal.tsx
  src/components/mysetting/PasswordInput.tsx
  src/components/mysetting/RemoveAccount.tsx
  src/components/mysetting/inputTask.tsx
  src/components/mysetting/usermockdata.ts
  src/hooks/mysetting/usePasswordChange.ts
  src/hooks/mysetting/usePasswordCheck.ts
  src/libs/axios/axiosInstance.ts
  src/pages/test/sidebar/index.tsx
  src/types/mysetting/settingData.ts
Labels: Feat, Fix, !BREAKING CHANGE

#41 ZERO-102 : Navbar API 연동
  src/components/@shared/MockUserData.ts
  src/components/@shared/NavBar.tsx
  src/hooks/mysetting/useUserData.ts
  src/pages/_app.tsx
  src/types/mysetting/settingData.ts
Labels: Fix, !BREAKING CHANGE

#42 ZERO-92 : 계정설정페이지 비밀번호 에러 모달 추가
  src/components/mysetting/PasswordChange.tsx
Labels: Refactor

#43 ZERO-95 : 팀페이지 모달, 드롭다운 연결 및 폴더 구조 변경
  public/icons/button_edit.svg
  src/components/@shared/BasicDropdown.tsx
  src/components/@shared/NavBar.tsx
  src/components/@shared/ProfileImageInput.tsx
  src/components/team/AddTeamModal.tsx
  src/components/team/EditDropdown.tsx
  src/components/team/TeamBanner.tsx
  src/components/team/banner/DeleteTeamModal.tsx
  src/components/team/banner/EditTeamModal.tsx
  src/components/team/banner/TeamBanner.tsx
  src/components/team/member/ExileDropdown.tsx
  src/components/team/member/ExileUserModal.tsx
  src/components/team/member/GetUserDetailModal.tsx
  src/components/team/member/InvitationModal.tsx
  src/components/team/member/MemberBox.tsx
  src/components/team/member/MemberList.tsx
  src/components/team/taskList/AddTaskListModal.tsx
  src/components/team/taskList/DeleteTaskListModal.tsx
  src/components/team/taskList/EditTaskListModal.tsx
  src/components/team/taskList/TaskBar.tsx
  src/components/team/taskList/TaskList.tsx
  src/components/team/teamInfo.ts
  src/pages/[teamid]/index.tsx
Labels: Feat, Rename

#40 ZERO-45: 달력 기능 구현
  package-lock.json
  package.json
  public/icons/calender_arrow_left.svg
  public/icons/calender_arrow_right.svg
  src/components/tasks/UI/Calender.tsx
  src/contexts/DateContext.tsx
  src/styles/calendar.module.css
  src/styles/globals.css
Labels: Feat, Design

#45 ZERO -114 : nav bar 오류수정
  src/components/@shared/NavBar.tsx
Labels: Fix

#47 ZERO-116: 회원가입, 로그인 리팩토링
  src/components/auth/SignInForm.tsx
  src/components/auth/SignUpForm.tsx
  src/libs/axios/axiosInstance.ts
  src/stores/useUserStore.ts
Labels: Refactor

#44 ZERO-108 : 게시판 페이지 퍼블리싱
  public/icons/heart.svg
  public/icons/ic_medal.svg
  src/components/article/ArrayDropdown.tsx
  src/components/article/ArticleCard.tsx
  src/pages/article/[id].tsx
  src/pages/article/index.tsx
  src/pages/article/new.tsx
Labels: Design

#46 ZERO-58: 비밀번호 재설정 페이지 퍼블리싱
  src/components/auth/ResetPasswordForm.tsx
  src/pages/resetpassword/index.tsx
Labels: Design

#49 ZERO-59: 비밀번호 재설정 페이지 api 기능 구현
  src/components/auth/ResetPasswordForm.tsx
  src/components/auth/SignInForm.tsx
  src/pages/reset-password/index.tsx
Labels: Feat

#52 ZERO-65: 할 일 생성 모달 및 폼 제출 로직 추가 & 디자인 변경
  package-lock.json
  package.json
  src/components/tasks/AddTaskForm.tsx
  src/components/tasks/Layout/TaskDate.tsx
  src/components/tasks/Layout/TaskList.tsx
  src/components/tasks/UI/AddTaskButton.tsx
  src/components/tasks/UI/AddTaskListButton.tsx
  src/components/tasks/UI/AddTaskModal.tsx
  src/components/tasks/UI/Calender.tsx
  src/components/tasks/UI/CalenderButton.tsx
  src/components/tasks/UI/CreateTask.tsx
  src/components/tasks/UI/CreateTaskList.tsx
  src/components/tasks/UI/TaskCard.tsx
  src/components/tasks/UI/WeeklySelector.tsx
  src/constants/initValues.ts
  src/contexts/DateContext.tsx
  src/hooks/useModal.tsx
  src/pages/[teamid]/tasks/index.tsx
  src/styles/calendar.module.css
  src/styles/globals.css
  src/types/tasks/TaskListDto.ts
  src/utils/getModalClass.tsx
Labels: Feat, Chore, Design

#53 ZERO-96 : 팀페이지 api연결 - 팀정보
  next.config.mjs
  package-lock.json
  package.json
  src/api/imageAPI.ts
  src/api/team/teamAPI.ts
  src/components/team/AddTeamModal.tsx
  src/components/team/banner/DeleteTeamModal.tsx
  src/components/team/banner/EditTeamModal.tsx
  src/components/team/banner/TeamBanner.tsx
  src/libs/axios/axiosInstance.ts
  src/pages/[teamid]/index.tsx
  src/pages/_app.tsx
  src/stores/teamStore.ts
Labels: Feat, Fix, Chore, Refactor

#51 ZERO-119: axios interceptor 수정
  src/libs/axios/axiosInstance.ts
Labels: Fix

#50 ZERO-62: 비밀번호 재설정 페이지 유효성 검사
  src/components/auth/ResetPasswordForm.tsx
  src/components/auth/SignInForm.tsx
  src/components/auth/SignUpForm.tsx
Labels: Feat

#57 ZERO-60: 팀 생성하기 페이지 퍼블리싱
  src/components/addteam/AddTeamForm.tsx
  src/components/addteam/ParticipateTeamForm.tsx
  src/components/auth/ResetPasswordForm.tsx
  src/components/auth/SignInForm.tsx
  src/pages/addteam/index.tsx
  src/pages/addteam/participate.tsx
Labels: Design

#54 ZERO-109 : 게시판 페이지 api 연동
  package-lock.json
  package.json
  src/api/article/articlecardAPI.tsx
  src/components/@shared/Input.tsx
  src/components/article/ArrayDropdown.tsx
  src/components/article/ArticleCard.tsx
  src/components/article/BestCard.tsx
  src/hooks/article/useArticleCard.tsx
  src/pages/article/index.tsx
  src/pages/article/newarticle.tsx
  src/stores/useCardStore.ts
  src/types/article/CardType.ts
Labels: Feat

#55 ZERO-125 : Navbar 팀 메뉴 트리거 로직 추가
  src/components/@shared/NavBar.tsx
  src/components/mysetting/PasswordChange.tsx
  src/components/mysetting/RemoveAccount.tsx
Labels: Fix, Refactor

#56 ZERO-74: 리스트페이지 관련 모달 추가 & 캘린더 디자인 보완
  src/components/tasks/AddTaskForm.tsx
  src/components/tasks/Calender.tsx
  src/components/tasks/CheckBox.tsx
  src/components/tasks/Layout/TaskDate.tsx
  src/components/tasks/Layout/TaskList.tsx
  src/components/tasks/Pagination.tsx
  src/components/tasks/TaskCard.tsx
  src/components/tasks/UI/AddTaskListButton.tsx
  src/components/tasks/UI/AddTaskListModal.tsx
  src/components/tasks/UI/CalenderButton.tsx
  src/components/tasks/UI/CheckBox.tsx
  src/components/tasks/UI/DeleteTaskModal.tsx
  src/components/tasks/UI/EditTaskModal.tsx
  src/components/tasks/UI/TaskCard.tsx
  src/components/tasks/WeeklySelector.tsx
  src/components/team/EditDropdown.tsx
  src/hooks/useDropdownModals.tsx
  src/styles/globals.css
Labels: Feat, Rename, Design

#62 ZERO-112 : 팀페이지 api연결 - 할일목록 (+멤버초대)
  src/api/tasks/taskListAPI.ts
  src/api/team/memberAPI.ts
  src/components/team/Report.tsx
  src/components/team/banner/DeleteTeamModal.tsx
  src/components/team/banner/EditTeamModal.tsx
  src/components/team/member/ExileUserModal.tsx
  src/components/team/member/InvitationModal.tsx
  src/components/team/taskList/AddTaskListModal.tsx
  src/components/team/taskList/DeleteTaskListModal.tsx
  src/components/team/taskList/EditTaskListModal.tsx
  src/components/team/taskList/TaskBar.tsx
  src/components/team/taskList/TaskList.tsx
  src/pages/[teamid]/index.tsx
  src/stores/teamStore.ts
Labels: Feat

#61 ZERO-61: 팀 생성하기 및 참여하기 페이지 API 연동
  src/api/addteam/participateTeamAPI.ts
  src/components/addteam/AddTeamForm.tsx
  src/components/addteam/ParticipateTeamForm.tsx
Labels: Feat

#68 ZERO-132 : 팀페이지 유효성검사 및 팀 리스트 페이지 제작 (!타 컴포넌트 변경사항 있음!)
  public/images/team_none.png
  public/images/team_none_mb.png
  public/images/team_none_tb.png
  src/api/tasks/taskAPI.ts
  src/api/team/memberAPI.ts
  src/components/@shared/NavBar.tsx
  src/components/@shared/NavBar_Team.tsx
  src/components/@shared/ProfileImageInput.tsx
  src/components/auth/SignInForm.tsx
  src/components/auth/SignUpForm.tsx
  src/components/team/AddTeamModal.tsx
  src/components/team/InvalidAccessModal.tsx
  src/components/team/banner/DeleteTeamModal.tsx
  src/components/team/banner/EditTeamModal.tsx
  src/components/team/banner/TeamBanner.tsx
  src/components/team/member/MemberBox.tsx
  src/components/team/myteam/EmptyTeamPage.tsx
  src/components/team/myteam/TeamBox.tsx
  src/components/team/taskList/AddTaskListModal.tsx
  src/components/team/taskList/EditTaskListModal.tsx
  src/components/team/taskList/TaskBar.tsx
  src/components/team/taskList/TaskList.tsx
  src/hooks/useValidation.tsx
  src/pages/[teamid]/index.tsx
  src/pages/myteam/index.tsx
  src/stores/teamStore.ts
  src/utils/getTimeAgo.ts
Labels: Feat

#69 ZERO-131: 회원가입, 로그인 리팩토링
  src/api/auth/authAPI.ts
  src/components/addteam/AddTeamForm.tsx
  src/components/addteam/ParticipateTeamForm.tsx
  src/components/auth/ResetPasswordForm.tsx
  src/components/auth/SignInForm.tsx
  src/components/auth/SignUpForm.tsx
  src/pages/resetpassword/index.tsx
Labels: Refactor

#70 ZERO-128 : 게시글 댓글 api 연동
  src/api/article/CommentCardAPI.tsx
  src/api/article/articlecardAPI.tsx
  src/components/@shared/NavBar.tsx
  src/components/article/ArticleCard.tsx
  src/components/article/CommentCardDeletModal.tsx
  src/components/article/CommentForm.tsx
  src/components/article/CommentList.tsx
  src/components/article/DetailCard.tsx
  src/hooks/article/useArticleDelet.tsx
  src/hooks/article/useArticleDetail.tsx
  src/hooks/article/useCommentCard.tsx
  src/pages/article/[articleId].tsx
  src/types/article/CommentType.ts
Labels: Feat

#72 ZERO-139 : 게시글 쓰기 페이지 퍼블리싱
  src/pages/article/newarticle.tsx
Labels: Design

#74 ZERO-140 : 게시글 작성 api 연동
  public/icons/x_white.svg
  src/api/article/newarticleAPI.tsx
  src/components/article/NewArticleImage.tsx
  src/hooks/article/useNewArticle.tsx
  src/pages/article/newarticle.tsx
Labels: Feat

#71 ZERO-136 : 팀페이지 할일목록 색상 추가 (+navbar 수정)
  src/components/@shared/Dropdown.tsx
  src/components/@shared/NavBar.tsx
  src/components/@shared/NavBar_Team.tsx
  src/components/@shared/SideBar.tsx
  src/components/team/AddTeamModal.tsx
  src/components/team/banner/EditTeamModal.tsx
  src/components/team/member/ExileDropdown.tsx
  src/components/team/member/MemberBox.tsx
  src/components/team/taskList/AddTaskListModal.tsx
  src/components/team/taskList/DeleteTaskListModal.tsx
  src/components/team/taskList/EditTaskListModal.tsx
  src/components/team/taskList/TaskBar.tsx
  src/components/team/taskList/TaskList.tsx
  src/components/team/taskList/tagColors.ts
  src/hooks/useValidation.tsx
  src/styles/scroll.module.css
Labels: Feat

#75 ZERO-140 [fix] : lint로인한 alert 모달 변경
  src/api/mysetting/inputAPI.ts
  src/components/@shared/SideBar.tsx
  src/components/article/CommentForm.tsx
  src/components/article/NewArticleImage.tsx
  src/components/auth/ResetPasswordForm.tsx
  src/components/mysetting/inputTask.tsx
  src/pages/article/newarticle.tsx
Labels: Fix

#80 ZERO-57: 간편 로그인(OAuth)
  next.config.mjs
  src/api/auth/authAPI.ts
  src/components/auth/GoogleOauthButton.tsx
  src/components/auth/KaKaoOauthButton.tsx
  src/components/auth/ResetPasswordForm.tsx
  src/components/auth/SignUpForm.tsx
  src/components/auth/SocialSignUpForm.tsx
  src/pages/oauth/google.tsx
  src/pages/oauth/kakao.tsx
  src/pages/oauth/signup/google.tsx
  src/pages/oauth/signup/kakao.tsx
Labels: Feat

#79 ZERO-145 : 팀페이지 스크롤기능 추가 및 자잘한 디자인 수정
  src/components/team/banner/DeleteTeamModal.tsx
  src/components/team/banner/TeamBanner.tsx
  src/components/team/member/GetUserDetailModal.tsx
  src/components/team/member/MemberBox.tsx
  src/components/team/member/MemberList.tsx
  src/components/team/taskList/TaskList.tsx
  src/styles/scroll.module.css
Labels: Fix, Design

#81 ZERO-145 : 로딩스피너 일부 적용
  public/images/loading1.png
  src/components/@shared/LoadingSpinner.tsx
  src/components/@shared/NavBar_Team.tsx
  src/components/team/myteam/TeamBox.tsx
  src/pages/[teamid]/index.tsx
  src/pages/myteam/index.tsx
  src/pages/test/loading.tsx
  src/styles/carAnimation.module.css
Labels: Design

#73 ZERO-120: 리스트페이지 API 연동 & taskSideBar 추가
  next.config.mjs
  package-lock.json
  src/api/tasks/commentAPI.ts
  src/api/tasks/taskAPI.ts
  src/api/tasks/taskListAPI.ts
  src/components/home/Content.tsx
  src/components/tasks/AddTaskForm.tsx
  src/components/tasks/CheckBox.tsx
  src/components/tasks/Layout/TaskDate.tsx
  src/components/tasks/Layout/TaskList.tsx
  src/components/tasks/TaskCard.tsx
  src/components/tasks/TaskComments.tsx
  src/components/tasks/TaskSideBar.tsx
  src/components/tasks/UI/AddTaskButton.tsx
  src/components/tasks/UI/AddTaskListModal.tsx
  src/components/tasks/UI/CalenderButton.tsx
  src/components/tasks/UI/DeleteTaskModal.tsx
  src/components/tasks/UI/EditTaskModal.tsx
  src/components/tasks/WeeklySelector.tsx
  src/components/tasks/mockdata.ts
  src/components/team/taskList/AddTaskListModal.tsx
  src/components/team/taskList/DeleteTaskListModal.tsx
  src/components/team/taskList/EditTaskListModal.tsx
  src/components/team/taskList/TaskList.tsx
  src/constants/initValues.ts
  src/contexts/DateContext.tsx
  src/contexts/TaskListContext.tsx
  src/pages/[teamid]/tasks.tsx
  src/pages/[teamid]/tasks/index.tsx
  src/pages/_app.tsx
  src/stores/taskListStore.ts
  src/stores/teamStore.ts
  src/types/tasks/TaskListDto.ts
  src/types/tasks/commentDto.ts
  src/types/tasks/taskDto.ts
  src/utils/apiCall.ts
  src/utils/getFormattedDate.tsx
  src/utils/toKSTISOString.ts
Labels: Feat, Refactor

#83 ZERO-144 : 좋아요 기능 구현
  public/icons/heartRed.svg
  src/components/article/ArticleCard.tsx
  src/components/article/BestCard.tsx
  src/components/article/DetailCard.tsx
  src/components/article/Heart.tsx
  src/hooks/article/useArticleDetail.tsx
Labels: Feat, Fix

#82 ZERO-146 : 팀페이지 드롭다운메뉴 연동
  package-lock.json
  package.json
  src/components/@shared/NavBar_Team.tsx
  src/components/@shared/createTeamOption.tsx
  src/components/team/banner/TeamBanner.tsx
  src/components/team/member/GetUserDetailModal.tsx
  src/components/team/member/ProfileImageModal.tsx
  src/stores/teamStore.ts
Labels: Feat, Design
